version: '3.8'

services:
  copin-tests:
    build: .
    container_name: copin-test-runner
    environment:
      # Environment variables for tests
      - HEADLESS_MODE=true
      - DEFAULT_BROWSER=chrome
      - THREAD_COUNT=1
      - PARALLEL_MODE=methods
      - RETRY_COUNT=2
      - DEFAULT_TIMEOUT=30
      - IMPLICIT_WAIT=10
      - SCREENSHOT_ON_FAILURE=true
      - API_BASE_URL=https://api.copin.io
      - WEB_BASE_URL=https://copin.io
      - EMAIL=${EMAIL}
      - DEFAULT_OTP=${DEFAULT_OTP}
      - ENVIRONMENT=prod
    volumes:
      # Mount test results and reports
      - ./target:/app/target
      - ./allure-results:/app/allure-results
      # Mount .env file if exists
      - ./.env:/app/.env:ro
    networks:
      - test-network
    # Run specific test suite
    command: ["/app/start.sh", "./mvnw", "test", "-Dsurefire.suiteXmlFiles=src/test/resources/testSuites/CopinApiDataTest.xml"]

  # Optional: Selenium Grid for parallel testing
  selenium-hub:
    image: selenium/hub:4.15.0-20231110
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - test-network

  selenium-chrome:
    image: selenium/node-chrome:4.15.0-20231110
    container_name: selenium-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - test-network

networks:
  test-network:
    driver: bridge