version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: copin-automation:dev
    container_name: copin-tests-dev
    env_file:
      - .env
    environment:
      - HEADLESS_MODE=true
      - DEFAULT_BROWSER=chrome
      - THREAD_COUNT=${THREAD_COUNT:-1}
    volumes:
      # Mount results để xem realtime
      - ./target:/app/target
      - ./allure-results:/app/allure-results
      # Mount source code để không cần rebuild khi sửa code (dev only)
      - ./src:/app/src:ro
      - ./pom.xml:/app/pom.xml:ro
    command: mvn test -Papi  # Default chạy API tests
    networks:
      - test-network

  # Allure service để xem report realtime
  allure:
    image: frankescobar/allure-docker-service:latest
    container_name: allure-report
    ports:
      - "5050:5050"  # Allure UI
      - "4040:4040"  # Allure API
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/default-reports
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
    networks:
      - test-network

networks:
  test-network:
    driver: bridge